play_motion:
  motions:
    fist_bump:
      joints: ['arm_right_1_joint', 'arm_right_2_joint', 'arm_right_3_joint', 'arm_right_4_joint', 'arm_right_5_joint', 'arm_right_6_joint', 'arm_right_7_joint', 'hand_right_thumb_joint', 'hand_right_index_joint', 'hand_right_middle_joint']
      points:
      - positions: [-0.401, 0.25, -0.1, 0.611, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0]
        time_from_start: 0.0
      - positions: [-0.403, 0.61, 0.06, 2.081, -0.96, -0.0, -0.0, 1.35, 3.97, 3.7]
        time_from_start: 2.0
      - positions: [-0.403, 0.61, 0.06, 2.081, -0.96, -0.0, -0.0, 1.35, 3.97, 3.7]
        time_from_start: 2.5
      - positions: [0.45, 0.61, -0.74, 1.77, -0.96, -0.0, -0.0, 1.35, 3.97, 3.7]
        time_from_start: 3.5
      - positions: [-0.403, 0.61, 0.06, 2.081, -0.96, -0.0, -0.0, 1.35, 3.97, 3.7]
        time_from_start: 4.5
      - positions: [-0.401, 0.25, -0.1, 0.611, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0]
        time_from_start: 6.0

      meta:
        name: Fist bump
        usage: demo
        description: 'Fist bump'
